// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.4
// source: tardigrades.proto

package rpc

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DeploymentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token     string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                          // 用户TOKEN
	ProjectId string `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"` // 项目ID
	Data      []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                            // zip 压缩文件
}

func (x *DeploymentReq) Reset() {
	*x = DeploymentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tardigrades_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeploymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentReq) ProtoMessage() {}

func (x *DeploymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_tardigrades_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentReq.ProtoReflect.Descriptor instead.
func (*DeploymentReq) Descriptor() ([]byte, []int) {
	return file_tardigrades_proto_rawDescGZIP(), []int{0}
}

func (x *DeploymentReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DeploymentReq) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeploymentReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeploymentResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueueId string `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"` // 排队ID
	Queue   int32  `protobuf:"varint,2,opt,name=queue,proto3" json:"queue,omitempty"`                   // 队伍长度
	Error   string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                    // 错误信息  , == "" 则没有错误
}

func (x *DeploymentResp) Reset() {
	*x = DeploymentResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tardigrades_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeploymentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentResp) ProtoMessage() {}

func (x *DeploymentResp) ProtoReflect() protoreflect.Message {
	mi := &file_tardigrades_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentResp.ProtoReflect.Descriptor instead.
func (*DeploymentResp) Descriptor() ([]byte, []int) {
	return file_tardigrades_proto_rawDescGZIP(), []int{1}
}

func (x *DeploymentResp) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

func (x *DeploymentResp) GetQueue() int32 {
	if x != nil {
		return x.Queue
	}
	return 0
}

func (x *DeploymentResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token   string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                    // 用户TOKEN
	QueueId string `protobuf:"bytes,2,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"` // 排队ID
}

func (x *StatsReq) Reset() {
	*x = StatsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tardigrades_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsReq) ProtoMessage() {}

func (x *StatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_tardigrades_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsReq.ProtoReflect.Descriptor instead.
func (*StatsReq) Descriptor() ([]byte, []int) {
	return file_tardigrades_proto_rawDescGZIP(), []int{2}
}

func (x *StatsReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *StatsReq) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

type StatsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Queue int32  `protobuf:"varint,1,opt,name=queue,proto3" json:"queue,omitempty"` // 队伍长度
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`  // 错误信息  , == "" 则没有错误
}

func (x *StatsResp) Reset() {
	*x = StatsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tardigrades_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResp) ProtoMessage() {}

func (x *StatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_tardigrades_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResp.ProtoReflect.Descriptor instead.
func (*StatsResp) Descriptor() ([]byte, []int) {
	return file_tardigrades_proto_rawDescGZIP(), []int{3}
}

func (x *StatsResp) GetQueue() int32 {
	if x != nil {
		return x.Queue
	}
	return 0
}

func (x *StatsResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_tardigrades_proto protoreflect.FileDescriptor

var file_tardigrades_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x61, 0x72, 0x64, 0x69, 0x67, 0x72, 0x61, 0x64, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x22, 0x58, 0x0a, 0x0d, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x57, 0x0a, 0x0e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x71, 0x75, 0x65, 0x75, 0x65, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x3b, 0x0a, 0x08, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x19, 0x0a,
	0x08, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x71, 0x75, 0x65, 0x75, 0x65, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x32, 0x6c, 0x0a, 0x0b, 0x54, 0x61, 0x72, 0x64, 0x69, 0x67, 0x72, 0x61, 0x64, 0x65, 0x73,
	0x12, 0x35, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x13, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x12, 0x0d, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a,
	0x0e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x42,
	0x07, 0x5a, 0x05, 0x2e, 0x3b, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tardigrades_proto_rawDescOnce sync.Once
	file_tardigrades_proto_rawDescData = file_tardigrades_proto_rawDesc
)

func file_tardigrades_proto_rawDescGZIP() []byte {
	file_tardigrades_proto_rawDescOnce.Do(func() {
		file_tardigrades_proto_rawDescData = protoimpl.X.CompressGZIP(file_tardigrades_proto_rawDescData)
	})
	return file_tardigrades_proto_rawDescData
}

var file_tardigrades_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tardigrades_proto_goTypes = []interface{}{
	(*DeploymentReq)(nil),  // 0: rpc.DeploymentReq
	(*DeploymentResp)(nil), // 1: rpc.DeploymentResp
	(*StatsReq)(nil),       // 2: rpc.StatsReq
	(*StatsResp)(nil),      // 3: rpc.StatsResp
}
var file_tardigrades_proto_depIdxs = []int32{
	0, // 0: rpc.Tardigrades.Deployment:input_type -> rpc.DeploymentReq
	2, // 1: rpc.Tardigrades.Stats:input_type -> rpc.StatsReq
	1, // 2: rpc.Tardigrades.Deployment:output_type -> rpc.DeploymentResp
	3, // 3: rpc.Tardigrades.Stats:output_type -> rpc.StatsResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tardigrades_proto_init() }
func file_tardigrades_proto_init() {
	if File_tardigrades_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tardigrades_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeploymentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tardigrades_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeploymentResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tardigrades_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tardigrades_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tardigrades_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tardigrades_proto_goTypes,
		DependencyIndexes: file_tardigrades_proto_depIdxs,
		MessageInfos:      file_tardigrades_proto_msgTypes,
	}.Build()
	File_tardigrades_proto = out.File
	file_tardigrades_proto_rawDesc = nil
	file_tardigrades_proto_goTypes = nil
	file_tardigrades_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TardigradesClient is the client API for Tardigrades service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TardigradesClient interface {
	Deployment(ctx context.Context, in *DeploymentReq, opts ...grpc.CallOption) (*DeploymentResp, error)
	Stats(ctx context.Context, in *StatsReq, opts ...grpc.CallOption) (*StatsResp, error)
}

type tardigradesClient struct {
	cc grpc.ClientConnInterface
}

func NewTardigradesClient(cc grpc.ClientConnInterface) TardigradesClient {
	return &tardigradesClient{cc}
}

func (c *tardigradesClient) Deployment(ctx context.Context, in *DeploymentReq, opts ...grpc.CallOption) (*DeploymentResp, error) {
	out := new(DeploymentResp)
	err := c.cc.Invoke(ctx, "/rpc.Tardigrades/Deployment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tardigradesClient) Stats(ctx context.Context, in *StatsReq, opts ...grpc.CallOption) (*StatsResp, error) {
	out := new(StatsResp)
	err := c.cc.Invoke(ctx, "/rpc.Tardigrades/Stats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TardigradesServer is the server API for Tardigrades service.
type TardigradesServer interface {
	Deployment(context.Context, *DeploymentReq) (*DeploymentResp, error)
	Stats(context.Context, *StatsReq) (*StatsResp, error)
}

// UnimplementedTardigradesServer can be embedded to have forward compatible implementations.
type UnimplementedTardigradesServer struct {
}

func (*UnimplementedTardigradesServer) Deployment(context.Context, *DeploymentReq) (*DeploymentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deployment not implemented")
}
func (*UnimplementedTardigradesServer) Stats(context.Context, *StatsReq) (*StatsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}

func RegisterTardigradesServer(s *grpc.Server, srv TardigradesServer) {
	s.RegisterService(&_Tardigrades_serviceDesc, srv)
}

func _Tardigrades_Deployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeploymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TardigradesServer).Deployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Tardigrades/Deployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TardigradesServer).Deployment(ctx, req.(*DeploymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tardigrades_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TardigradesServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Tardigrades/Stats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TardigradesServer).Stats(ctx, req.(*StatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tardigrades_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Tardigrades",
	HandlerType: (*TardigradesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deployment",
			Handler:    _Tardigrades_Deployment_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _Tardigrades_Stats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tardigrades.proto",
}
